substitutions:
  _TF_ACTION: "plan"

steps:
  # Step 1: Download tfvars
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Download tfvars
    entrypoint: "sh"
    args:
      - "-c"
      - |
        gsutil cp gs://terraform_folder/tfvars/terraform.tfvars .
    dir: terraform-vm

  # Step 2: Terraform init
  - name: hashicorp/terraform:1.12
    id: Init
    entrypoint: "sh"
    args:
      - "-c"
      - terraform init
    dir: terraform-vm

  # Step 3: Conditional Terraform plan
  - name: hashicorp/terraform:1.12
    id: Plan or Apply
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ "$_TF_ACTION" = "plan" ]; then
          terraform plan -var-file="terraform.tfvars" -out=tfplan
          terraform show -no-color tfplan > tfplan.txt
          gsutil cp tfplan.txt gs://terraform_folder/tfvars/tfplan.txt
        elif [ "$_TF_ACTION" = "apply" ]; then
          terraform apply -auto-approve -var-file="terraform.tfvars"
        else
          echo "❌ Unknown action: $_TF_ACTION"
          exit 1
        fi
    dir: terraform-vm

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
