steps:
  # Step 1: Download tfvars from GCS
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Download tfvars
    entrypoint: "sh"
    args:
      - "-c"
      - |
        gsutil cp gs://terraform_folder/tfvars/terraform.tfvars .

  # Step 2: Terraform init
  - name: hashicorp/terraform:light
    id: Init
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform init

  # Step 3: Terraform plan using downloaded tfvars
  - name: hashicorp/terraform:light
    id: Plan
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform plan -var-file="terraform.tfvars"

  # Step 4: Terraform apply
  - name: hashicorp/terraform:light
    id: Apply
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform apply -auto-approve -var-file="terraform.tfvars"

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s