steps:
  # Step 1: Download tfvars from GCS using Cloud SDK
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Download tfvars
    entrypoint: "sh"
    args:
      - "-c"
      - |
        gsutil cp gs://terraform_folder/tfvars/terraform.tfvars .
    dir: terraform-vm

  # Step 2: Terraform init
  - name: hashicorp/terraform:1.12
    id: Init
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform init
    dir: terraform-vm

  # Step 3: Terraform plan and save plan.out
  - name: hashicorp/terraform:1.12
    id: Plan
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform plan -var-file="terraform.tfvars" -out=tfplan
        terraform show -no-color tfplan > tfplan.txt
    dir: terraform-vm

  # Step 4: Upload plan.out to GCS using Cloud SDK
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Upload plan
    entrypoint: "sh"
    args:
      - "-c"
      - |
        gsutil cp tfplan.txt gs://terraform_folder/tfvars/tfplan.txt
    dir: terraform-vm


  # Step 4: Terraform apply
  # - name: hashicorp/terraform:light
  #   id: Apply
  #   entrypoint: "sh"
  #   args:
  #     - "-c"
  #     - |
  #       terraform apply -auto-approve -var-file="terraform.tfvars"
  #   dir: terraform-vm

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s